---
- name: Test DNS Forwarder Config
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars.yml

  tasks:
    - name: Create forwarders_string variable
      ansible.builtin.set_fact:
        forwarders_string: "{{ '; '.join(forwarders) }};"

    - name: Create test conf file
      ansible.builtin.template:
        src: bind/named.conf.j2
        dest: test.conf
